<!-- main -->
<img src="img/souv-col.jpeg"/>
<section>
    <h1>2 TESTS</h1>
    <h2></h2>
    <p>lorem ipsum dolor sin amet .....  </p>
</section>

<section>
    <figure><img src=""><figcaption>C'était le 00/00/1971</figcaption></figure>
</section>

<section>
    <h2>C'était le 26 Avril 1971</h2>
    <p>Classe de 4° collège Ste Thérèse le 26/04/1971 en sortie pédagogique à la <a href="https://www.poterie-village.fr/">poterie des 3 ilets</a> .</p>
    <p>Notre professeur était Mr POMMIER Michel .</p>
</section>

<section>
    <h2>Aujourd'hui</h2>
    <p>Je suis Eric HONORE et j'essaie de retrouver mes anciens camarades.</p>
    <p>M. POMMIER et moi nous nous sommes déjà revus récemment: le 00/00/2019, au XXXXX pour l'évènement XXXXX</p>
</section>
<section>
    <h2>Demain</h2>
    <p>Je souhaite organiser à l'occasion des 50 ans de cette photo un évènement regroupant les élèves de cette photo .</p>
    <p>Ce sera le 00/00/0000 à XXXX ENDRROIT</p>
    <p>Pour cela nous essayons de retrouver les élèves de cette photo ...</p>
    <p>Si vous vous reconnaissez ou si vous reconnaissez quelqu'un <a href="mailto:eric.honore@live.fr">envoyez-nous un mail</a></p>
    <p>Ou remplissez le formulaire <a href="index.php?page=contact">ici</a></p>
</section>

<section>
    <h2>Reprenons contact</h2>
    <p>Vous avez un commentaire ?</p>
    <p>Vous souhaitez laisser un message ?</p>
    <p><a href="index.php?page=contact">Contactez-nous</a>, et nous vous repondrons avec plaisir</p>
</section>