<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>1971 - 2020</title>
    <link rel="icon" href=""/> <!-- FAVICON -->
    <!--      GOOGLE  FONT COINY      -->
    <link href="https://fonts.googleapis.com/css?family=Coiny" rel="stylesheet">
    <!--      GOOGLE  FONT Saira Stencil One      -->
    <link href="https://fonts.googleapis.com/css?family=Saira+Stencil+One&display=swap" rel="stylesheet">
     <!--      FONT AWESOME       -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
	<!-- LIENS JAVA SCRIPT  -->
     <script type ="text/javascript" src=""></script>
     <!-- LIENS CSS   -->
    <link rel="stylesheet" href="css/normalize.css" > <!-- ===NORMALIZE===  -->
    <link rel="stylesheet" type="text/css" href="css/style.css" ><!-- TOUJOURS TOUJOURS le dernier appelé -->
</head>
<body>
    <header>
        <h1><a>50 ans déja !</a></h1>
        <nav>
            <a href="index.php?page=home">Accueil</a>
            <a href="index.php?page=contact">Contactez-nous</a>
        </nav>
    </header>
    <main>
        <?php include $template.'.phtml' ?>
    </main>
    <footer>
        
    </footer>
</body>
</html>